In [ ]:
dizi = [1.1,2.2,3.3,4.4,5.5]
matris = [[1,2],[3,4],[5,6]]

In [18]:
import numpy as np
np_dizi = np.array(dizi,dtype="int64")
np_matris = np.array(matris)
np_matris2 = np.matrix(matris)
print(type(dizi))
print(type(np_dizi))
print(type(np_matris))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
print(dizi)
print(np_dizi)
print(np_matris)
print(np_matris2)

[1.1, 2.2, 3.3, 4.4, 5.5]
[1 2 3 4 5]
[[1.2 2. ]
 [3.  4. ]
 [5.  6. ]]
[[1.2 2. ]
 [3.  4. ]
 [5.  6. ]]


In [24]:
print(np.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((3,5)))

[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [41]:
print(np.full((3,3),65537,dtype=np.int16))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [34]:
print(np.eye(3,dtype=np.int8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [43]:
print(np.random.rand(3,3))

[[0.66503424 0.41381274 0.75630856]
 [0.61200074 0.49970424 0.33158042]
 [0.41846053 0.54420786 0.27978948]]


In [ ]:
dizi = np.array([1,2,3,4,5,6,7,8])
print(dizi + 1)
print(dizi * 2)
print(dizi > 5)
print(dizi[dizi>0])

[2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16]
[False False False False False  True  True  True]
[6 7 8]


In [56]:
matris1 = np.matrix([[2,1],[4,3]])
matris2 = np.matrix([[1,2],[3,4]])
dizi1 = np.array([[2,1],[4,3]])
dizi2 = np.array([[1,2],[3,4]])


In [ ]:
print(dizi1 * dizi2)
print(dizi1 @ dizi2)



[[ 2  2]
 [12 12]]
[[ 5  8]
 [13 20]]
1


In [59]:
print(matris1 * matris2)

[[ 5  8]
 [13 20]]


In [64]:
class_to_index = {"dog":1,"cat":0}
index_to_class = ["cat","dog"]
print(index_to_class[np.argmax([0.375,0.625])])

dog


In [68]:
dizi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dizi.reshape((1,9)))

[[1 2 3 4 5 6 7 8 9]]


In [69]:
dizi = np.array([1,2,3,4,5,6,7,8,9])
matris = dizi.reshape((3,3))
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
pl = np.poly1d([2,4,1])
print(pl)
print(pl.order)
print(pl.roots)
print(pl.deriv(1))
print(pl.integ(1))

   2
2 x + 4 x + 1
2
[-1.70710678 -0.29289322]
 
4 x + 4
        3     2
0.6667 x + 2 x + 1 x
